### ISSUE TITLE
Suggest merging with my similar repo

### ISSUE THREAD

**Issue by mikeizbicki** [dessalines/essays#21]
I have a repo at https://github.com/mikeizbicki/american-shit that is similar to your `us-atrocities.md` file.  My repo seems to have a few incidents not already in yours.  I suggest we merge them together.  Since your repo is more popular than mine, I suggest simply adding the material from mine into yours and keeping yours as the main source.  I do think your phrasing of 'atrocities' is a bit too strong for some of the things in my repo though.  So I suggest that we renaim your file to `american-shit.md` to be slightly broader in scope.

What do you think?

**Comment by dessalines** [comment]
I agree that american shit is potentially much broader in scope than just atrocities. I've wanted to add things like this wave of white supremacist terrorism recently, but my list is limited by things performed by authority figures. 

I kinda do want mine to stay just a source of *atrocities committed by authorities*, because normies do need stark examples, but I do think there's potentially some stuff in yours that I could use. I'll make a todo for myself to go over your list and add anything that makes sense into mine. 

And of course, feel free to take anything from my list and add to yours too.

**Comment by mikeizbicki** [comment]
Glad it was useful :)

**Comment by dessalines** [comment]
Ya it was, thanks!
