### ISSUE TITLE
list of atrocities to add

### ISSUE THREAD

**Issue by Jaksuhn** [dessalines/essays#52]
Poisoning of alcohol during prohbition (up to 10k deaths) - http://www.slate.com/articles/health_and_science/medical_examiner/2010/02/the_chemists_war.html

Officer found not guilty after impregnating a 15yo - http://www.dailymail.co.uk/news/article-5645553

Police show up at wrong address, shoot the dog and execute the man there with a bullet in the back of the head - https://www.cnn.com/2017/07/29/us/mississippi-man-shot-dead/index.html

The actions of Jacob Smith in the Philippine-American War - most notably his orders to "kill everyone over the age of ten" - https://en.wikipedia.org/wiki/Jacob_H._Smith

Pardoning of Unit 731 - https://en.wikipedia.org/wiki/American_cover-up_of_Japanese_war_crimes

Forced/coerced sterilisation of latina women - https://en.wikipedia.org/wiki/Madrigal_v._Quilligan

**Comment by dessalines** [comment]
Thank you so much for these, I'll get them added shortly.

**Comment by Anarcho-Bolshevik** [comment]
FDA complicit in the risk of breast cancer: https://www.projectcensored.org/?p=444

Similar to the above: https://www.projectcensored.org/?p=5728

‘Since the APA has been able to maintain a low media profile on its efforts to bring back electroshock therapy, the number of patients receiving such therapy has been on the rise, and it is now estimated that 100,000 people, mostly middle-aged, white [women], receive it annually.’ https://www.projectcensored.org/?p=13585

‘Japanese […] statistics compiled by the police indicate no fewer than 6,000 cases of crime since 1972, including violence and rape. One said case was of an Australian who in the year 2002 was raped by a United States sailor. This woman’s name is Catherine Fisher and she was one of many [women] to speak up about these heinous crimes in Japan. In 1995 there was even a rape of a 12-year-old by three U.S. servicemen. This case caused such a controversy that it’s a wonder our troops are still in Japan.’ https://www.projectcensored.org/?p=3858

General overview of misogyny that Yank troops committed against Iraqis: https://www.projectcensored.org/?p=10043

Carnal abuse that the troops committed within the military itself: https://www.projectcensored.org/?p=2218

Middle schools suspending black students at a disproportionate rate, especially if they’re girls: https://www.projectcensored.org/?p=5731

Yank hospitals would rather deport women than heal them: https://www.projectcensored.org/?p=20168

More to come.
