### ISSUE TITLE
Copyright issues

### ISSUE THREAD

**Issue by temtemy** [dessalines/essays#60]
Let's start with the repo's license. I think it's inappropriate to use GPLv3 for a repo only containing essays. It should only be used for software, which have source code. I recommend CC-BY-SA-4.0 instead. It does what you want: allow commercial and noncommercial use, redistribution, and modification, as long as re-users give proper attribution, and derivative works to be under the same license. Without the unnecessary terms from the GPL.

Then I noticed that you copied word-by-word from the English Wikipedia. You should give proper attribution to the Wikipedians, as required by their CC-BY-SA-3.0. If you decide to still use the GPL, you must also include a link to the source code of the article, as you would be relicensing the Wikipedia article to CC-BY-SA-4.0 which will allow relicensing to GPLv3 (but not vice versa).

Lastly, [left_anticommunism_parenti.md](https://github.com/dessalines/essays/blob/master/left_anticommunism_parenti.md) is obviously not your work, so you should make a disclaimer that that file is not licensed under your chosen license, so that the re-users will not be confused. The same with the photos in the file.

**Comment by dessalines** [comment]
The parenti article has it's source listed at the top.

As far as GPL vs CC, it's a larger debate, but these actually could be considered code or "representations" of text, since they're markdown files. The markdown files are the source code. I specifially **don't want** the type of open CC license, since it would allow this to be used for commercial use, unless they include the source, and the same license.

A small # of the sentences are taken from wiki, but the articles are always linked.
